// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Web client ID required for Google Sign-In + Firebase Auth (idToken).
  static const String googleWebClientId =
      '1097671455586-b1veh4vi8lc3gmleeggivf5d6pe175dm.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk1A_nVzo-l-0SzWdbhuitjlPTI31hUqo',
    appId: '1:1097671455586:web:5dfa32eee784fd6ef0b23b',
    messagingSenderId: '1097671455586',
    projectId: 'electricity-bill-calcula-514f0',
    authDomain: 'electricity-bill-calcula-514f0.firebaseapp.com',
    storageBucket: 'electricity-bill-calcula-514f0.firebasestorage.app',
    measurementId: 'G-YPNEX5W459',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJisPj6WyYMzWzjioBDdgCwxuPrvMKBN4',
    appId: '1:1097671455586:android:1491d2c53dfb4315f0b23b',
    messagingSenderId: '1097671455586',
    projectId: 'electricity-bill-calcula-514f0',
    storageBucket: 'electricity-bill-calcula-514f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmhAEzJODIXZgn1Ml6xRBCkwlZZ28HupQ',
    appId: '1:1097671455586:ios:6f89e8b159117bc7f0b23b',
    messagingSenderId: '1097671455586',
    projectId: 'electricity-bill-calcula-514f0',
    storageBucket: 'electricity-bill-calcula-514f0.firebasestorage.app',
    iosClientId: '1097671455586-3r1sfa5577gk4uj251fmekb3ub1033ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.electricityBillCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmhAEzJODIXZgn1Ml6xRBCkwlZZ28HupQ',
    appId: '1:1097671455586:ios:6f89e8b159117bc7f0b23b',
    messagingSenderId: '1097671455586',
    projectId: 'electricity-bill-calcula-514f0',
    storageBucket: 'electricity-bill-calcula-514f0.firebasestorage.app',
    iosClientId: '1097671455586-3r1sfa5577gk4uj251fmekb3ub1033ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.electricityBillCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk1A_nVzo-l-0SzWdbhuitjlPTI31hUqo',
    appId: '1:1097671455586:web:462572e04e9bc056f0b23b',
    messagingSenderId: '1097671455586',
    projectId: 'electricity-bill-calcula-514f0',
    authDomain: 'electricity-bill-calcula-514f0.firebaseapp.com',
    storageBucket: 'electricity-bill-calcula-514f0.firebasestorage.app',
    measurementId: 'G-7JR6SBFYEK',
  );
}
